imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
assetic:
    debug:          false
    use_controller:
       enabled: '%kernel.debug%'
       profiler: false
    bundles:
       - AppBundle
       - AirCorsicaXKPlanBundle

#accelerator_cache:
#    host: demo.xkplan.sitec.fr
#    web_dir: %kernel.root_dir%/../web

#web_profiler:
#    toolbar: true
#    intercept_redirects: false
#
#framework:
#    profiler:
#        only_exceptions: false
