# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.amos.xsd.path: '%kernel.root_dir%/../web/AMOS/transferFutureFlights_0.3.xsd'

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]