<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * AbstractCodeShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractCodeShareRepository extends \Doctrine\ORM\EntityRepository
{
}
