<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * AdresseSITARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseSITARepository extends \Doctrine\ORM\EntityRepository
{
}
