<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * AffretementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffretementRepository extends \Doctrine\ORM\EntityRepository
{
}
