<?php

namespace AirCorsica\XKPlanBundle\Repository;
use AirCorsica\XKPlanBundle\Entity\Template;

/**
 * AvionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findParCompagnieTrieParOrdre($idCompagnie){

        $qb = $this->createQueryBuilder('a');
        $qb->where('a.compagnie = '.$idCompagnie);
        $qb->orderBy("a.ordre", 'ASC');
        $query = $qb->getQuery();
        $result = $query->execute();

        return $result;
    }

    public function findAllTrieParAffreteOrdreNom(){

        $qb = $this->createQueryBuilder('a');
        $qb->orderBy("a.affrete", 'ASC');
        $qb->addOrderBy("a.ordre", 'ASC');
        $qb->addOrderBy("a.nom", 'ASC');
        $query = $qb->getQuery();
        $result = $query->execute();

        return $result;
    }

    public function findAllTrieParOrdre(){

        $qb = $this->createQueryBuilder('a');
        $qb->orderBy("a.ordre", 'ASC');
        $query = $qb->getQuery();
        $result = $query->execute();

        return $result;
    }

    public function findNotCompagnie($idCompagnie){

        $qb = $this->createQueryBuilder('a');
        $qb->where('a.compagnie != '.$idCompagnie);
        $query = $qb->getQuery();
        $result = $query->execute();

        return $result;
    }


    public function getAvionsImmobilisesForDate(\DateTime $jourCalendrier, Template $template){

        $jourCalendrier->setTime(0,0,0); //$jourCalendrier est un dateTime

        $qb = $this->createQueryBuilder('a');
        $qb->leftjoin('AirCorsica\XKPlanBundle\Entity\PeriodeImmobilisation','i', 'WITH', 'a.id = i.avion');
        $qb->leftjoin('AirCorsica\XKPlanBundle\Entity\Periode','p', 'WITH', 'i.id = p.id');
        $qb->where($qb->expr()->between(':jour_calendrier', 'p.dateDebut', 'p.dateFin'));
        $qb->andWhere('i.template = :template');
        $qb->setParameter('jour_calendrier', $jourCalendrier, \Doctrine\DBAL\Types\Type::DATETIME);
        $qb->setParameter('template',$template);
        $qb->orderBy("a.compagnie", 'DESC');
        $query = $qb->getQuery();
        $result = $query->execute();

        return $result;
    }

}
