<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * CodeShareVolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeShareVolRepository extends \Doctrine\ORM\EntityRepository
{
//    /**
//     * @param int $idVol
//     * @return array
//     */
//    public function  getCodesShareVolFromVol($id)
//    {
//        $qb = $this->createQueryBuilder('code_share_vol');
//        $qb->join('code_share_vol.vols','vols');
//        $qb->where('vols.id = :vol');
//        $qb->setParameter('vol', $id);
//        $query = $qb->getQuery();
//        $result = $query->getArrayResult();
//        return $result;
//    }
}
