<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * CodeInterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeInterneRepository extends \Doctrine\ORM\EntityRepository
{
}
