<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * CodeSharePrechargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeSharePrechargeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $libelle
     * @return array
     */
  public function  getCodesPrechargesFromLibelle($libelle)
  {
      $qb = $this->createQueryBuilder('code_share_precharge');
      $qb->join("code_share_precharge.codeInterne",'code_interne');
      $qb->where('code_interne.libelle LIKE :libelle');
      $qb->setParameter('libelle','%'.$libelle.'%');
      $query = $qb->getQuery();
      $result = $query->getArrayResult();
      return $result;
  }

}
