<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * GroupeSITARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeSITARepository extends \Doctrine\ORM\EntityRepository
{
}
