<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * NatureDeVolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureDeVolRepository extends \Doctrine\ORM\EntityRepository
{
}
