<?php

namespace AirCorsica\XKPlanBundle\Repository;
use AirCorsica\XKPlanBundle\Entity\Avion;
use AirCorsica\XKPlanBundle\Entity\Template;

/**
 * PeriodeImmobilisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeImmobilisationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getImmoForAvionAndTemplate(Avion $avion, Template $template){

        $qb = $this->createQueryBuilder('pi');
        $qb->join('pi.avion','a');
        $qb->where('pi.avion = :avion');
        $qb->andWhere('pi.template = :template');
        $qb->setParameter('avion',$avion);
        $qb->setParameter('template',$template);
        $query = $qb->getQuery();
        $result = $query->execute();

        return $result;
    }
}
