<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * PeriodeDeVolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeDeVolRepository extends \Doctrine\ORM\EntityRepository
{
}
