<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * APeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeRepository extends \Doctrine\ORM\EntityRepository
{
}
