<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * TypeAvionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAvionRepository extends \Doctrine\ORM\EntityRepository
{
}
