<?php

namespace AirCorsica\XKPlanBundle\Repository;

/**
 * TypeDeVolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDeVolRepository extends \Doctrine\ORM\EntityRepository
{
}
