amos_index:
    path:     /
    defaults: { _controller: "AirCorsicaXKPlanBundle:Amos:index" }
    methods:  GET

amos_generate:
    path:     /generate
    defaults: { _controller: "AirCorsicaXKPlanBundle:Amos:generate" }
    methods:  GET