codeinterne_index:
    path:     /
    defaults: { _controller: "AirCorsicaXKPlanBundle:CodeInterne:index" }
    methods:  GET

codeinterne_codessharecsv:
    path:     /codessharecsv
    defaults: { _controller: "AirCorsicaXKPlanBundle:CodeInterne:codessharecsv" }
    methods:  GET

codeinterne_show:
    path:     /{id}/show
    defaults: { _controller: "AirCorsicaXKPlanBundle:CodeInterne:show" }
    methods:  GET

codeinterne_new:
    path:     /new
    defaults: { _controller: "AirCorsicaXKPlanBundle:CodeInterne:new" }
    methods:  [GET, POST]

codeinterne_edit:
    path:     /{id}/edit
    defaults: { _controller: "AirCorsicaXKPlanBundle:CodeInterne:edit" }
    methods:  [GET, POST]

codeinterne_delete:
    path:     /{id}/delete
    defaults: { _controller: "AirCorsicaXKPlanBundle:CodeInterne:delete" }
    #methods:  DELETE
