groupesita_index:
    path:     /
    defaults: { _controller: "AirCorsicaXKPlanBundle:GroupeSITA:index" }
    methods:  GET

groupesita_show:
    path:     /{id}/show
    defaults: { _controller: "AirCorsicaXKPlanBundle:GroupeSITA:show" }
    methods:  GET

groupesita_new:
    path:     /new
    defaults: { _controller: "AirCorsicaXKPlanBundle:GroupeSITA:new" }
    methods:  [GET, POST]
    options:
        expose: true

groupesita_edit:
    path:     /{id}/edit
    defaults: { _controller: "AirCorsicaXKPlanBundle:GroupeSITA:edit" }
    methods:  [GET, POST]

groupesita_delete:
    path:     /{id}/delete
    defaults: { _controller: "AirCorsicaXKPlanBundle:GroupeSITA:delete" }
    methods:  [GET, DELETE]

groupesita_csv:
    path:     /groupesitacsv
    defaults: { _controller: "AirCorsicaXKPlanBundle:GroupeSITA:groupesitacsv" }
    methods:  [GET]
