periodedevol_index:
    path:     /
    defaults: { _controller: "AirCorsicaXKPlanBundle:PeriodeDeVol:index" }
    methods:  GET

periodedevol_show:
    path:     /{id}/show
    defaults: { _controller: "AirCorsicaXKPlanBundle:PeriodeDeVol:show" }
    methods:  GET

periodedevol_new:
    path:     /new
    defaults: { _controller: "AirCorsicaXKPlanBundle:PeriodeDeVol:new" }
    methods:  [GET, POST]

periodedevol_edit:
    path:     /{id}/edit
    defaults: { _controller: "AirCorsicaXKPlanBundle:PeriodeDeVol:edit" }
    methods:  [GET, POST]

periodedevol_delete:
    path:     /{id}/delete
    defaults: { _controller: "AirCorsicaXKPlanBundle:PeriodeDeVol:delete" }
    methods:  DELETE
