tempsdevol_index:
    path:     /
    defaults: { _controller: "AirCorsicaXKPlanBundle:TempsDeVol:index" }
    methods:  GET

tempsdevol_show:
    path:     /{id}/show
    defaults: { _controller: "AirCorsicaXKPlanBundle:TempsDeVol:show" }
    methods:  GET

tempsdevol_new:
    path:     /new
    defaults: { _controller: "AirCorsicaXKPlanBundle:TempsDeVol:new" }
    methods:  [GET, POST]

tempsdevol_edit:
    path:     /{id}/edit
    defaults: { _controller: "AirCorsicaXKPlanBundle:TempsDeVol:edit" }
    methods:  [GET, POST]
    options :
        expose: true

tempsdevol_delete:
    path:     /{id}/delete
    defaults: { _controller: "AirCorsicaXKPlanBundle:TempsDeVol:delete" }
    methods:  [DELETE, GET]

tempsdevol_init:
    path:     /init
    defaults: { _controller: "AirCorsicaXKPlanBundle:TempsDeVol:init" }
    methods:  POST
    options:
        expose: true
