typedevol_index:
    path:     /
    defaults: { _controller: "AirCorsicaXKPlanBundle:TypeDeVol:index" }
    methods:  GET

typedevol_show:
    path:     /{id}/show
    defaults: { _controller: "AirCorsicaXKPlanBundle:TypeDeVol:show" }
    methods:  GET

typedevol_new:
    path:     /new
    defaults: { _controller: "AirCorsicaXKPlanBundle:TypeDeVol:new" }
    methods:  [GET, POST]

typedevol_edit:
    path:     /{id}/edit
    defaults: { _controller: "AirCorsicaXKPlanBundle:TypeDeVol:edit" }
    methods:  [GET, POST]

typedevol_delete:
    path:     /{id}/delete
    defaults: { _controller: "AirCorsicaXKPlanBundle:TypeDeVol:delete" }
    #methods:  DELETE

typedevol_deletemasse:
    path:     /deletemasse
    defaults: { _controller: "AirCorsicaXKPlanBundle:TypeDeVol:deletemasse" }
    methods:  [GET, POST]